
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 06 13:59:17 ECT 2022
//----------------------------------------------------

package AnalizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIGITO = 8;
  public static final int ARITMETICOS = 5;
  public static final int P_RESERVADA = 10;
  public static final int ERROR = 9;
  public static final int P_COMA = 6;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ASIGNACION = 2;
  public static final int PARENTESIS_C = 4;
  public static final int NOMBRE = 7;
  public static final int PARENTESIS_A = 3;
}

