package AnalizadorSintactico;
import java_cup.runtime.Symbol;

parser code
{:
    private Symbol s;
    public void syntax_error(Symbol s){
        this.s = s;
    }
    public Symbol getS(){
        return this.s;
    }
:};

terminal IGUAL, LLAVE_A, LLAVE_C, PARENTESIS_A, PARENTESIS_C, ARITMETICOS, P_COMA, NOMBRE, DIGITO, ERROR;
non terminal INICIO, VARIABLE, P_RESERVADA;
INICIO ::= VARIABLE;
VARIABLE ::= NOMBRE |NOMBRE VARIABLE;

