
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 23 22:58:00 ECT 2022
//----------------------------------------------------

package AnalizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIGITO = 12;
  public static final int DERIVADA = 15;
  public static final int PRESAS = 6;
  public static final int P_RESERVADA = 14;
  public static final int ERROR = 13;
  public static final int P_COMA = 10;
  public static final int MULTIPLICACION = 7;
  public static final int EOF = 0;
  public static final int CONCATENADOR = 9;
  public static final int error = 1;
  public static final int ASIGNACION = 2;
  public static final int DEPREDADORES = 5;
  public static final int PARENTESIS_C = 4;
  public static final int NOMBRE = 11;
  public static final int RESTA = 8;
  public static final int PARENTESIS_A = 3;
}

