
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 04 14:59:46 ECT 2022
//----------------------------------------------------

package AnalizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ECAD = 20;
  public static final int MULTIPLICACION = 8;
  public static final int ERROR = 14;
  public static final int P_RESERVADA = 15;
  public static final int ASIGNACION = 2;
  public static final int DERIVADA = 16;
  public static final int TCP = 18;
  public static final int NOMBRE = 12;
  public static final int EOF = 0;
  public static final int DIGITO = 13;
  public static final int PRESA = 21;
  public static final int TIEMPO = 5;
  public static final int CONCATENADOR = 10;
  public static final int PARENTESIS_C = 4;
  public static final int error = 1;
  public static final int PARENTESIS_A = 3;
  public static final int DEPREDADORES = 6;
  public static final int ECDP = 19;
  public static final int P_COMA = 11;
  public static final int PRESAS = 7;
  public static final int TCD = 17;
  public static final int DEPREDADOR = 22;
  public static final int RESTA = 9;
}

